SELECT 
    case
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 then '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 then '2Q' 
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 then '3Q'
        ELSE '4Q'
        end 
        as QUARTER
        , count(ID) AS ECOLI_COUNT
from ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER